### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by PavelBocharov** [PavelBocharov/TelegramBot#33]

**Comment by PavelBocharov** [comment]
```
telegrambot-app-1        | 2023-06-08 07:56:43,736 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Get message: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,745 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Check callback query: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,748 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Check admin: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,755 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Pars text: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,759 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Check photo: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,770 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Check video: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,773 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Check gif (animation): {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,774 | DEBUG | o.m.t.b.s.l.LoggerService | [LoggerService.java:28] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] Check document: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,776 | WARN  | o.m.t.b.s.l.LoggerService | [LoggerService.java:32] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] [!!!] So, interesting situation: {"rqUuid":"6ec653fc-1ea9-4b97-a6ce-8727f331f6b6","isSuccess":false}
telegrambot-app-1        | 2023-06-08 07:56:43,781 | ERROR | o.m.t.b.s.l.LoggerService | [LoggerService.java:36] | [6ec653fc-1ea9-4b97-a6ce-8727f331f6b6] java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.mar.telegram.bot.service.bot.dto.MessageStatus.getMsgUserId()" is null
telegrambot-app-1        | 	at org.mar.telegram.bot.service.bot.TelegramBotService.workWithMessage(TelegramBotService.java:45)
telegrambot-app-1        | 	at org.mar.telegram.bot.service.bot.TelegramBotService.worker(TelegramBotService.java:28)
telegrambot-app-1        | 	at org.mar.telegram.bot.service.bot.TelegramBotService.lambda$postInit$0(TelegramBotService.java:20)
telegrambot-app-1        | 	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:73)
telegrambot-app-1        | 	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:49)
telegrambot-app-1        | 	at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:53)
telegrambot-app-1        | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
telegrambot-app-1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
telegrambot-app-1        | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
telegrambot-app-1        | 	at java.base/java.lang.Thread.run(Unknown Source)
telegrambot-app-1        | 

```
